name: Generate PHP SDK

on:
  push:
    branches:
      - fix-npm-registry-url

jobs:
  generate-php-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Generate PHP SDK
        run: npm run generate

      - name: Commit Generated PHP SDK
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git diff --staged --quiet || git commit -m "Generate PHP SDK"
          git push


